[package]
name = "htree"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
byteorder = "*"
easybench = "1"
geo-types = "*"

[dependencies]
h3ron = { version = "0.14.0" }
serde = { version = "1", optional = true, features = ["derive"] }

[features]
default = []
with-serde = ["h3ron/use-serde", "serde"]
