[package]
name = "hexset"
version = "0.1.0"
authors = ["Jay Kickliter <jay@kickliter.com>"]
categories = ["science", "data-structures"]
edition = "2018"
exclude = ["/test/*"]
readme = "README.md"
keywords = ["geo", "geography", "geospatial", "gis", "h3"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/jaykickliter/hexset"
description = """
A HexSet is datastructure for hit-testing geographic regions.
Regions are internally represented as a tree of H3 polygons.
"""

[package.metadata.docs.rs]
all-features = true

[features]
default = []
serde-support = ["h3ron/use-serde", "serde"]

[dependencies]
h3ron = { version = "0.14" }
serde = { version = "1", optional = true, features = ["derive"] }

[dev-dependencies]
easybench = "1"
geo-types = "*"
h3-lorawan-regions = { git = "https://github.com/JayKickliter/h3-lorawan-regions.git", branch = "main" }
